apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gluster-nginx-dm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gluster-storage-volume
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: gluster-storage-volume
        persistentVolumeClaim:
          claimName: gluster-nginx-pvc
