apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv1
spec:
  capacity:
    storage: 200G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.155
    path: "/data/pvdata/efk/elasticsearch/pv1"
