apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-server #这里和storageclass.yaml文件中的provisioner要一致
            - name: NFS_SERVER
              value: 192.168.1.155  #NFS_SERVER的地址
            - name: NFS_PATH
              value: /data/pvdata   #NFS_SERVER共享的目录
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.1.155   #NFS_SERVER的地址
            path: /data/pvdata      #NFS_SERVER共享的目录
